PORTNAME=	qobuz-player
DISTVERSIONPREFIX=	v
DISTVERSION=	0.3.2-2
CATEGORIES=	audio

MAINTAINER=	agrajag9@a9development.com
COMMENT=	High resolution audio player backed by Qobuz
WWW=		https://github.com/SofusA/qobuz-player

LICENSE=	GPLv3

USES=		cargo
USE_GITHUB=	yes
GH_ACCOUNT=	SofusA

.include <bsd.port.mk>
