PORTNAME=	arrpc
DISTVERSION=	3.6.0
CATEGORIES=	net-im

MAINTAINER=	agrajag9@a9development.com
COMMENT=	open implementation of Discord's local RPC servers

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		electron:build

BUILD_DEPENDS=	npm>=0:www/npm

USE_GITHUB=	yes
GH_ACCOUNT=	OpenAsar
GH_PROJECT=	arrpc



.include <bsd.port.mk>
